version: '3'
services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d/cdn.conf:/etc/nginx/conf.d/cdn.conf
      - ./nginx/assets:/usr/share/nginx/html/assets
      - ./nginx/log:/var/log/nginx
    container_name: nginx
    networks:
      - backend
    depends_on:
       - app
       - app1

  app:
    build:
      context: app
      dockerfile: Dockerfile
    environment:
      PORT: 3000
    container_name: app
    ports:
      - 3000:3000
    networks:
      - backend

  app1:
    build:
      context: app
      dockerfile: Dockerfile
    environment:
      PORT: 3001
    container_name: app1
    ports:
      - 3001:3001
    networks:
      - backend

networks: # 가장 기본적인 bridge 네트워크
  backend:
    driver: bridge